name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Sử dụng phiên bản mới nhất của actions/checkout để hỗ trợ Node.js 20
      - uses: actions/checkout@v3

      # Tạo hình ảnh rắn
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Tronglai301
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Hiển thị trạng thái build để dễ dàng debug nếu có vấn đề
      - run: git status

      # Đẩy các thay đổi
      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
